from enum import StrEnum

class JobStatus(StrEnum):
    PENDING = "PENDING"; QUEUED = "QUEUED"; CLAIMED = "CLAIMED"; PREPARING = "PREPARING"; RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"; FAILED = "FAILED"; CANCELLED = "CANCELLED"; INTERRUPTED = "INTERRUPTED"

class JobType(StrEnum):
    STORY_GENERATION = "STORY_GENERATION"; CHARACTER_GENERATION = "CHARACTER_GENERATION"; CHARACTER_IMAGE = "CHARACTER_IMAGE"
    STORYBOARD = "STORYBOARD"; TTS = "TTS"; VIDEO = "VIDEO"; LIPSYNC = "LIPSYNC"; SUBTITLE = "SUBTITLE"; UPSCALE = "UPSCALE"; RENDER = "RENDER"
